### ISSUE TITLE
Where to get Apache Ignite version 2.7.0

### ISSUE THREAD

**Issue by zengxijin** [VeryFatBoy/ignite-ml-examples#1]
it seems Apache Ignite version 2.7.0 haven't release in maven repository

**Comment by VeryFatBoy** [comment]
Yes, 2.7 is not officially available yet. In the meantime, the way to get the Logistic Regression ML code working is to use the existing Ignite download and copy and paste the Java into the Ignite examples, modifying the package details as appropriate.

You can see that Logistic Regression is already available in Ignite:

https://github.com/apache/ignite/tree/master/examples/src/main/java/org/apache/ignite/examples/ml/regression/logistic

If you build and run the code from the Ignite examples, it will work even though 2.7 is not currently available.
